server:
  port: 8762
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/goldkunlun/cloud-config
          username: 769558579@qq.com
          password: w769558579
  application:
    name: cloud-config-server