server:
  port: 8762
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/goldkunlun/cloud-config
          username: 769558579@qq.com
          password: w769558579
  application:
    name: cloud-config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  boot:
    admin:
    url: http://localhost:8090
    username: user
    password: pass
management:
  security:
    enabled: false