server:
  port: 8762
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/goldkunlun/cloud-config
          username: 769558579@qq.com
          password: w769558579
  application:
    name: cloud-config-server
  boot:
    admin:
      url: http://192.168.0.119:8091
      username: user
      password: pass
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.119:8761/eureka
management:
  security:
    enabled: false